// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPfTfjKys1mPQE7LQ535gSgiHR-ZxLu8',
    appId: '1:528597463277:web:9367bf3bc41304d98e1ce4',
    messagingSenderId: '528597463277',
    projectId: 'ecolens-ai-18544',
    authDomain: 'ecolens-ai-18544.firebaseapp.com',
    storageBucket: 'ecolens-ai-18544.firebasestorage.app',
    measurementId: 'G-6MB4WMXWD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqREGr0Wy4AqtBSfb3vtmdihzXtHveULA',
    appId: '1:528597463277:android:93089eddf2b48ffc8e1ce4',
    messagingSenderId: '528597463277',
    projectId: 'ecolens-ai-18544',
    storageBucket: 'ecolens-ai-18544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKQqxyjSQpduZe1gSgaT-7wyJKT_ocuM',
    appId: '1:528597463277:ios:4deceb21c9f761b48e1ce4',
    messagingSenderId: '528597463277',
    projectId: 'ecolens-ai-18544',
    storageBucket: 'ecolens-ai-18544.firebasestorage.app',
    iosClientId: '528597463277-am5j3qic2rkqto28b7nar8qqhvsabdfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonScope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKQqxyjSQpduZe1gSgaT-7wyJKT_ocuM',
    appId: '1:528597463277:ios:4deceb21c9f761b48e1ce4',
    messagingSenderId: '528597463277',
    projectId: 'ecolens-ai-18544',
    storageBucket: 'ecolens-ai-18544.firebasestorage.app',
    iosClientId: '528597463277-am5j3qic2rkqto28b7nar8qqhvsabdfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonScope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPfTfjKys1mPQE7LQ535gSgiHR-ZxLu8',
    appId: '1:528597463277:web:1f1254dc30a829f78e1ce4',
    messagingSenderId: '528597463277',
    projectId: 'ecolens-ai-18544',
    authDomain: 'ecolens-ai-18544.firebaseapp.com',
    storageBucket: 'ecolens-ai-18544.firebasestorage.app',
    measurementId: 'G-YWYGTP4V3F',
  );
}
